#:kivy 1.10.0

<HomeScreen>:
    name: '_home_screen_'
    canvas.before:
        Color:
            # rgba: 0.5,0.75,1,1
            rgba: 0.422,0.176,0.336,1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            Label:
                id: home_screen_label
                text: "Hi, I'm the Home screen!"
        NavBar:
