#:kivy 1.10.0

<SpotifyScreen>:
    name: '_spotify_screen_'
    canvas.before:
        Color:
            # rgba: 0.533,0.786,0.694,1
            rgba: 0.18,0.46,0.21,1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            Label:
                id: spotify_screen_label
                text: "Hi, I'm the Spotify! screen!"
        NavBar: